version: '3.1'

services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    restart: always
    ports:
      - "443:443"
    volumes:
      - /Users/aalami/goinfre/data:/var/www/html/
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    depends_on:
      - maria-db
    container_name: wordpress
    build: ./wordpress/.
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /Users/aalami/goinfre/data:/var/www/html/
    env_file:
      - .env
    networks:
      - inception

  maria-db:
    container_name: maria-db
    build: ./maria-db/.
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception

networks:
  inception:
    driver: bridge
    name: inception_network